// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace studentiEF.Migrations
{
    [DbContext(typeof(StudentiContext))]
    partial class StudentiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CLasse", b =>
                {
                    b.Property<int>("ClasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sede")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sezione")
                        .HasColumnType("TEXT");

                    b.HasKey("ClasseId");

                    b.ToTable("Classi");
                });

            modelBuilder.Entity("Studente", b =>
                {
                    b.Property<string>("StudenteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudenteId");

                    b.ToTable("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
